package com.example.jblandii.protectora.peticionesBD;

public class Tags {

    public static final String SERVIDOR = "http://jblandii.dreamsappscreative.es/"; //LA IP DEL SERVIDOR
//        public static final String SERVIDOR = "http://192.168.0.22:8000/"; //LA IP DEL SERVIDOR

    public static final String USUARIO = "usuario",
            PASSWORD = "password",
            PASSWORD_ANTIGUA = "antigua",
            EMAIL_ANTIGUO = "antiguo",
            SIN_CONEXION_INTERNET = "Sin conexión a internet.",
            PASSWORD_NUEVA = "nueva",
            MEDIA = "static/media/",
            RED = "red",
            REDES = "redes",
            VALOR = "valor",
            EMAIL_NUEVO = "nuevo",
            USERNAME = "username",
            EMISARIO = "emisario",
            PK = "pk",
            HORA = "hora",
            MASCOTA = "mascota",
            RAZA = "raza",
            COLOR = "color",
            ANIMAL = "animal",
            EDAD = "edad",
            PELAJE = "pelaje",
            SEXO = "sexo",
            TAMANO = "tamano",
            PESO = "peso",
            ENFERMEDAD = "enfermedad",
            ESTADO = "estado",
            VACUNA = "vacuna",
            CHIP = "chip",
            ID_PROTECTORA = "id_protectora",
            PROTECTORA = "protectora",
            MEGUSTA = "me_gusta",
            DESCRIPCION = "descripcion",
            COMUNIDAD_AUTONOMA = "comunidad_autonoma",
            FECHA = "fecha",
            COD_POSTAL = "codigo_postal",
            DIRECCION = "direccion",
            TELEFONO = "telefono",
            RESULTADO = "result",
            OK = "ok",
            OK_SIN_ANIMALES = "ok_sin_animales",
            OK_SIN_PROTECTORAS = "ok_sin_protectoras",
            ERROR = "error",
            MENSAJE = "message",
            MSN = "mensaje",
            USUARIOLOGUEADO = "Usuario logueado",
            USUARIO_ID = "usuario_id",
            NOMBRE = "nombre",
            APELLIDOS = "apellidos",
            COMUNIDAD_USUARIO = "comunidad_usuario",
            PROVINCIA_USUARIO = "provincia_usuario",
            TOKEN = "token",
            FOTO = "foto",
            EMAIL = "email",
            MSG = "message",
            COMUNIDADES = "comunidades",
            PROVINCIAS = "provincias",
            PROVINCIA = "provincia",
            TOKENFINGIDO = "tokenFingido",
            ID_COMUNIDAD = "id_comunidad",
            LISTA_ANIMALES = "lista_animales",
            LISTA_CONVERSACIONES = "lista_conversaciones",
            LISTA_PROTECTORAS = "lista_protectoras",
            TOKENFINGIDOGENERADO = "JAMAGELEjamagele";


    public static final String ERRORCONEXION = "error conexion";


    public static final int LOGIN = 1,
            REGISTRO = 3,
            REGISTRO_OK = 4,
            RECORDAR = 25,
            CAMBIAR_CONTRASENA = 26,
            CAMBIAR_EMAIL = 27,
            CAMBIAR_DATOS = 28,
            FILTRO_ANIMAL = 29,
            FILTRO_PROTECTORA = 30;
}
