package com.example.jblandii.protectora.peticionesBD;

public class Tags {

    //    public static final String SERVIDOR = "http://192.168.0.22:8000/"; //LA IP DEL SERVIDOR
    public static final String SERVIDOR = "http://192.168.1.22:8000/"; //LA IP DEL SERVIDOR

    public static final String USUARIO = "usuario",
            USUARIOS = "usuarios",
            PASSWORD = "password",
            PASSWORD_ANTIGUA = "antigua",
            EMAIL_ANTIGUO = "antiguo",
            SIN_CONEXION_INTERNET = "Sin conexión a internet.",
            PASSWORD_NUEVA = "nueva",
            MEDIA = "static/media/",
            RED = "red",
            REDES = "redes",
            VALOR = "valor",
            EMAIL_NUEVO = "nuevo",
            USERNAME = "username",
            NOMBREPROTECTORA = "nombre_protectora",
            EMISARIO = "emisario",
            PK = "pk",
            HORA = "hora",
            MASCOTA = "mascota",
            RAZA = "raza",
            COLOR = "color",
            ANIMAL = "animal",
            EDAD = "edad",
            EDADMENOS = "edad_menos",
            EDADMAS = "edad_mas",
            PELAJE = "pelaje",
            SEXO = "sexo",
            TAMANO = "tamano",
            PESO = "peso",
            ENFERMEDAD = "enfermedad",
            ESTADO = "estado",
            VACUNA = "vacuna",
            CHIP = "chip",
            ID_PROTECTORA = "id_protectora",
            PROTECTORA = "protectora",
            MEGUSTA = "me_gusta",
            DESCRIPCION = "descripcion",
            COMUNIDAD_AUTONOMA = "comunidad_autonoma",
            FECHA = "fecha",
            COD_POSTAL = "codigo_postal",
            DIRECCION = "direccion",
            TELEFONO = "telefono",
            RESULTADO = "result",
            OK = "ok",
            OK_SIN_ANIMALES = "ok_sin_animales",
            OK_SIN_PROTECTORAS = "ok_sin_protectoras",
            ERROR = "error",
            MENSAJE = "message",
            MSN = "mensaje",
            USUARIOLOGUEADO = "Usuario logueado",
            USUARIO_ID = "usuario_id",
            DESTINATARIO_ID = "destinatario_id",
            NOMBRE = "nombre",
            APELLIDOS = "apellidos",
            COMUNIDAD_USUARIO = "comunidad_usuario",
            PROVINCIA_USUARIO = "provincia_usuario",
            TOKEN = "token",
            TOKEN_ANDROID = "token_android",
            DEVICE_ID = "device_id",
            SEMANA = "semana",
            FOTO = "foto",
            URL = "url",
            TIPO = "tipo",
            BUSQUEDA = "busqueda",
            EMAIL = "email",
            ASUNTO = "asunto",
            MSG = "message",
            COMUNIDADES = "comunidades",
            PROVINCIAS = "provincias",
            PROVINCIA = "provincia",
            TOKENFINGIDO = "tokenFingido",
            ID_COMUNIDAD = "id_comunidad",
            ID_PROVINCIA = "id_provincia",
            LISTA_ANIMALES = "lista_animales",
            LISTA_MENSAJES = "lista_mensajes",
            LISTA_CONVERSACIONES = "lista_conversaciones",
            LISTA_PROTECTORAS = "lista_protectoras",
            TOKENFINGIDOGENERADO = "JAMAGELEjamagele";


    public static final String ERRORCONEXION = "error conexion";


    public static final int LOGIN = 1,
            LOGIN_OK = 2,
            REGISTRO = 3,
            REGISTRO_OK = 4,
            REGISTRO_CANCELADO = 5,
            SERVICIO_START = 6,
            SERVICIO_STOP = 7,
            SERVICIO_DESCONECTAR = 8,
            SERVICIO_BINDER = 9,
            SERVICIO_BINDER_OK = 10,
            SERVICIO_BINDER_FAIL = 11,
            SERVICIO_BIND_COMENTARIOS = 24,
            SERVICIO_UNBIND_COMENTARIOS = 25,
            SALIR = 12,
            FIRMA = 13,
            PERFIL = 14,
            PASSCAMBIADA = 15,
            USUARIO_NO_LOGUEADO = 16,
            AVISOS_CARGADOS = 17,
            AVISOS_NO_CARGADOS = 18,
            CERRAR_DIALOG = 19,
            MENSAJES_CARGADOS = 20,
            MENSAJES_NO_CARGADOS = 21,
            SIN_AVISOS = 22,
            AVISOS_ACTUALIZADOS_DESDE_SERVICIO = 23,
            PARAR_SERVICIO_POR_ERROR_DE_TOKEN = 24,
            RECORDAR = 25,
            CAMBIAR_CONTRASENA = 26,
            CAMBIAR_EMAIL = 27,
            CAMBIAR_DATOS = 28,
            FILTRO_ANIMAL = 29;


    public static final String PREMIUM_ADMINISTRADO = "premium_administrado";


}
